from .blueprints import BlueprintCondition, BlueprintGate, BlueprintQuestion, BlueprintSection, BlueprintTemplate


BUSINESS_SYSTEM_TEMPLATE = BlueprintTemplate(
    "business-system-production", "1.0", "business_system", ["coding", "file_read", "file_write", "quality_gate"], [
        BlueprintSection("outcomes", "Business outcomes and ownership", ["functional"], questions=[BlueprintQuestion("outcome", "Which business outcome and owner define success?", "text", True), BlueprintQuestion("users", "Which user groups use the system?", "text", True)]),
        BlueprintSection("roles", "Roles and authorization", ["security", "functional"], gates=[BlueprintGate("authorization-review", "security", True, "Role and permission matrix approval required")], questions=[BlueprintQuestion("role-matrix", "What can each role view, create, change, approve, export, or delete?", "text", True)]),
        BlueprintSection("workflows", "Business workflows and states", ["functional"], questions=[BlueprintQuestion("critical-workflows", "List critical workflows, states, owners, and exceptions.", "text", True), BlueprintQuestion("approvals", "Which transitions require approval or segregation of duties?", "text", False)]),
        BlueprintSection("data", "Data model, retention, and audit", ["functional", "constraint", "security"], gates=[BlueprintGate("data-review", "approval", True, "Data ownership, retention, and audit requirements approved"), BlueprintGate("backup-restore", "backup", True, "Backup and restore test evidence required")], questions=[BlueprintQuestion("sensitive-data", "Which sensitive or regulated fields exist?", "text", True), BlueprintQuestion("retention", "What retention and deletion policies apply?", "text", True)]),
        BlueprintSection("reports", "Reports, exports, and reconciliation", ["functional", "quality"], questions=[BlueprintQuestion("reports", "Which reports, filters, exports, and reconciliation rules are required?", "text", True)]),
        BlueprintSection("integrations", "External integrations", ["functional", "constraint"], gates=[BlueprintGate("integration-failure", "test", True, "Retry, idempotency, timeout, and reconciliation failures tested")], questions=[BlueprintQuestion("systems", "Which systems, contracts, credentials, limits, and owners are involved?", "text", True)], condition=BlueprintCondition("network")),
        BlueprintSection("operations", "Operations, support, and deployment", ["production", "nonfunctional"], gates=[BlueprintGate("deployment", "deployment", True, "Repeatable deployment and rollback evidence required"), BlueprintGate("monitoring", "evidence", True, "Monitoring, alert ownership, and support runbook required")]),
        BlueprintSection("quality", "Quality and acceptance", ["quality", "security"], gates=[BlueprintGate("unit-tests", "test", True, "Core business rules covered by tests"), BlueprintGate("security", "security", True, "Security review completed"), BlueprintGate("performance", "performance", False, "Critical workflow performance measured")], questions=[BlueprintQuestion("acceptance", "Who accepts each workflow and with what evidence?", "text", True)]),
    ], {"stack_policy": "implementation_stack_not_prescribed"}
).validate()
