import React, { useEffect, useState } from 'react';
import { Archive, KeyRound, X } from 'lucide-react';
import type { ProviderInstance } from '../services/api';
import { api } from '../services/api';
import { StateNotice } from './StateNotice';
import { useDialogFocus } from '../accessibility';

export const ProviderDetail: React.FC<{ provider: ProviderInstance; onClose: () => void; onChanged: () => Promise<void> }> = ({ provider, onClose, onChanged }) => {
  const [current, setCurrent] = useState(provider);
  const [secrets, setSecrets] = useState<Array<{ reference: string; configured: boolean }>>([]);
  const [reference, setReference] = useState('API_KEY');
  const [value, setValue] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const { dialogRef, closeRef } = useDialogFocus(onClose);
  useEffect(() => { api.listProviderSecrets(current.id).then(setSecrets).catch(() => setSecrets([])); }, [current.id]);
  const act = async (callback: () => Promise<void>) => { setBusy(true); setError(''); try { await callback(); await onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Action failed.'); } finally { setBusy(false); } };
  const toggle = () => act(async () => setCurrent(await api.updateProviderInstance(current.id, { expected_revision: current.revision, user_enabled: !current.user_enabled })));
  const saveSecret = () => act(async () => { await api.setProviderSecret(current.id, reference, value); setValue(''); setSecrets(await api.listProviderSecrets(current.id)); const next = (await api.listProviderInstances()).find((item) => item.id === current.id); if (next) setCurrent(next); });
  const archive = () => { if (!window.confirm(`Archive ${current.name}? Bound credentials will be removed.`)) return; act(async () => { await api.archiveProviderInstance(current.id); onClose(); }); };
  return <div className="agent-detail-backdrop" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><section ref={dialogRef} tabIndex={-1} className="agent-detail surface-card" role="dialog" aria-modal="true" aria-labelledby="provider-detail-title"><header><div><span className={`status-badge model-${current.health_state}`}>{current.health_state}</span><h2 id="provider-detail-title">{current.name}</h2><p>{current.adapter_id} · protocol {current.protocol_version} · revision {current.revision}</p></div><button ref={closeRef} type="button" aria-label="Close" onClick={onClose}><X size={17} /></button></header>{error && <StateNotice state="error" title="Provider operation failed" detail={error} />}<div className="agent-detail-grid"><section><h3>Instance state</h3><dl><div><dt>Lifecycle</dt><dd>{current.lifecycle_status} · {current.user_enabled ? 'enabled' : 'disabled'}</dd></div><div><dt>Health checked</dt><dd>{current.health_checked_at ? new Date(current.health_checked_at).toLocaleString() : 'Never'}</dd></div><div><dt>Health expires</dt><dd>{current.health_expires_at ? new Date(current.health_expires_at).toLocaleString() : 'No current observation'}</dd></div></dl><button type="button" className="btn-secondary" onClick={toggle} disabled={busy}>{current.user_enabled ? 'Disable' : 'Enable'}</button></section><section><h3>Capabilities</h3><div className="asset-tags">{current.capabilities.length ? current.capabilities.map((item) => <span key={item}>{item}</span>) : <span>None declared</span>}</div><h3>Configuration</h3><pre className="agent-evidence-json">{JSON.stringify(current.configuration, null, 2)}</pre></section></div><section className="agent-secret-section"><h3><KeyRound size={14} /> Credential references</h3><p>Values are write-only and never returned.</p><div className="agent-secret-form"><input aria-label="Credential reference" className="input-text font-mono" value={reference} onChange={(event) => setReference(event.target.value.toUpperCase())} /><input aria-label="Credential value" className="input-text" type="password" value={value} onChange={(event) => setValue(event.target.value)} autoComplete="new-password" /><button type="button" className="btn-secondary" disabled={busy || !reference || !value} onClick={saveSecret}>Save</button></div><div className="agent-secret-list">{secrets.map((item) => <div key={item.reference}><span>{item.reference}</span><strong>{item.configured ? 'Configured' : 'Missing'}</strong></div>)}</div></section><footer><button type="button" className="btn-danger" disabled={busy} onClick={archive}><Archive size={13} /> Archive provider</button><span>{busy ? 'Working…' : 'Local provider registry'}</span></footer></section></div>;
};
